Add Renovate config
sapcc/go-makefile-maker pull request #14
Opened 2022-04-14 10:33 UTC by SuperSandro2000

Do less Ops and more Dev.

2022-04-14 14:07 UTC, talal requested changes
I am not familiar with Renovate Bot so I can't really comment on the config structure.

I think @majewsky did some reading on Renovate Bot so if you want to get his feedback then add him as reviewer otherwise feel free to go ahead with the merge.

2022-04-14 14:07 UTC, talal commented on internal/renovate/renovate.go
> +// Copyright 2021 SAP SE
The copyright year should be 2022.

2022-04-14 14:10 UTC, talal commented on internal/core/config.go
> +	Renovate       RenovateWorkflowConfig       `yaml:"renovate"`
I missed this earlier. The struct should not have workflow in its name as it is not a workflow.

2022-04-19 08:31 UTC, majewsky approved these changes
As discussed in Slack, please track bugfix releases for golang and alpine to simplify evidence collection for our patch management process. Otherwise, this is good to go in.

2022-04-19 09:04 UTC, merged