Makefile: split long line
sapcc/go-makefile-maker pull request #36
Opened 2022-06-16 19:01 UTC by talal

If `bininfo` package is used then the resulting ldflags can cause the
`go build` and `-test` lines to be very long. Splitting the line will
make it easier to read.

2022-06-20 13:26 UTC, majewsky requested changes
This does not seem to work as intended. The `\` remain in the quoted string, which confuses `go` since it does not expect backslashes sprinkled into the ldflags. (I tried in the limes repo.)

2022-06-20 23:48 UTC, talal commented
I tested with `limesctl` and it works as expected. I chose `limesctl` instead of Limes because I can get the version info from the former using a flag:

```
$ make
go build  -ldflags '-s -w \
                -X github.com/sapcc/go-api-declarations/bininfo.binName=limesctl \
                -X github.com/sapcc/go-api-declarations/bininfo.version=v3.0.0-92-g5e2af26 \
                -X github.com/sapcc/go-api-declarations/bininfo.commit=5e2af26659923c650ee211693d401d103d530301 \
                -X github.com/sapcc/go-api-declarations/bininfo.buildDate=2022-06-20T23:44:41Z ' -o build/limesctl .

$ ./build/limesctl --version
limesctl version v3.0.0-92-g5e2af26 built from Git commit 5e2af26659923c650ee211693d401d103d530301 on 2022-06-20T23:44:41Z
```

2022-06-21 07:44 UTC, majewsky commented
limesctl also errors out for me. I'm guessing /bin/sh works differently between Mac and Linux here?

```
$ make
go build  -ldflags '-s -w \
	-X github.com/sapcc/go-api-declarations/bininfo.binName=limesctl \
	-X github.com/sapcc/go-api-declarations/bininfo.version=v3.0.0-92-g5e2af26 \
	-X github.com/sapcc/go-api-declarations/bininfo.commit=5e2af26659923c650ee211693d401d103d530301 \
	-X github.com/sapcc/go-api-declarations/bininfo.buildDate=2022-06-21T07:43:42Z ' -o build/limesctl .
# github.com/sapcc/limesctl/v3
usage: link [options] main.o
  -B note
    	add an ELF NT_GNU_BUILD_ID note when using ELF
  -E entry
    	set entry symbol name
  -H type
    	set header type
  -I linker
    	use linker as ELF dynamic linker
  -L directory
    	add specified directory to library path
  -R quantum
    	set address rounding quantum (default -1)
  -T address
    	set text segment address (default -1)
  -V	print version and exit
  -X definition
    	add string value definition of the form importpath.name=value
  -a	no-op (deprecated)
  -asan
    	enable ASan interface
  -aslr
    	enable ASLR for buildmode=c-shared on windows (default true)
  -benchmark string
    	set to 'mem' or 'cpu' to enable phase benchmarking
  -benchmarkprofile base
    	emit phase profiles to base_phase.{cpu,mem}prof
  -buildid id
    	record id as Go toolchain build id
  -buildmode mode
    	set build mode
  -c	dump call graph
  -compressdwarf
    	compress DWARF if possible (default true)
  -cpuprofile file
    	write cpu profile to file
  -d	disable dynamic executable
  -debugtextsize int
    	debug text section max size
  -debugtramp int
    	debug trampolines
  -dumpdep
    	dump symbol dependency graph
  -extar string
    	archive program for buildmode=c-archive
  -extld linker
    	use linker when linking in external mode
  -extldflags flags
    	pass flags to external linker
  -f	ignore version mismatch
  -g	disable go package data checks
  -h	halt on error
  -importcfg file
    	read import configuration from file
  -installsuffix suffix
    	set package directory suffix
  -k symbol
    	set field tracking symbol
  -libgcc string
    	compiler support lib for internal linking; use "none" to disable
  -linkmode mode
    	set link mode
  -linkshared
    	link against installed Go shared libraries
  -memprofile file
    	write memory profile to file
  -memprofilerate rate
    	set runtime.MemProfileRate to rate
  -msan
    	enable MSan interface
  -n	dump symbol table
  -o file
    	write output to file
  -pluginpath string
    	full path name for plugin
  -r path
    	set the ELF dynamic linker search path to dir1:dir2:...
  -race
    	enable race detector
  -s	disable symbol table
  -strictdups int
    	sanity check duplicate symbol contents during object file reading (1=warn 2=err).
  -tmpdir directory
    	use directory for temporary files
  -v	print link trace
  -w	disable DWARF generation
make: *** [Makefile:34: build/limesctl] Error 2
```

2022-06-21 08:03 UTC, talal commented
Ahh, I see.

I tried to build the container image for Limes and `docker build` terminated with the same error as you mentioned above.

In this case, I'm closing the PR.

2022-06-21 08:03 UTC, closed without merging